/// A job listing generated by Gemini (AI-recommended, not a real posting).
class JobModel {
  final String id;
  final String title;
  final String company;
  final String location;
  final bool isRemote;
  final String jobType; // display-ready, e.g. "Full-Time", "Internship"
  final String salaryRange; // display-ready, e.g. "$90,000 - $120,000/year"
  final String description;
  final List<String> requiredSkills;
  final List<String> qualifications;
  final String? applyLink;
  final int? matchScore;
  final String? matchReason;
  final DateTime? postedAt;
  final DateTime? deadline;

  const JobModel({
    required this.id,
    required this.title,
    required this.company,
    required this.location,
    this.isRemote = false,
    required this.jobType,
    required this.salaryRange,
    required this.description,
    this.requiredSkills = const [],
    this.qualifications = const [],
    this.applyLink,
    this.matchScore,
    this.matchReason,
    this.postedAt,
    this.deadline,
  });

  factory JobModel.fromGemini(Map<String, dynamic> json, {required int index}) {
    final title = json['job_title'] as String? ?? 'Untitled role';
    final company = json['company_name'] as String? ?? 'Unknown company';
    final isRemote = json['is_remote'] as bool? ?? false;

    final postedDaysAgo = (json['posted_days_ago'] as num?)?.toInt() ?? 0;
    final deadlineDays = (json['application_deadline_days_from_now'] as num?)?.toInt();

    return JobModel(
      id: '${_slug(company)}-${_slug(title)}-'
          '${DateTime.now().millisecondsSinceEpoch}-$index',
      title: title,
      company: company,
      location: isRemote ? 'Remote' : (json['location'] as String? ?? 'Not specified'),
      isRemote: isRemote,
      jobType: json['job_type'] as String? ?? 'Full-Time',
      salaryRange: json['salary_range'] as String? ?? 'Not disclosed',
      description: json['description'] as String? ?? '',
      requiredSkills: _parseStringList(json['required_skills']),
      qualifications: _parseStringList(json['qualifications']),
      applyLink: _placeholderApplyLink(company, title),
      matchScore: (json['match_score'] as num?)?.toInt().clamp(0, 100).toInt(),
      matchReason: json['match_reason'] as String?,
      postedAt: DateTime.now().subtract(Duration(days: postedDaysAgo)),
      deadline: deadlineDays != null
          ? DateTime.now().add(Duration(days: deadlineDays))
          : null,
    );
  }

  String get employmentTypeLabel => jobType;

  String get salaryLabel => salaryRange;

  static String _placeholderApplyLink(String company, String title) {
    final query = Uri.encodeComponent('$company $title careers apply');
    return 'https://www.google.com/search?q=$query';
  }

  static String _slug(String value) {
    final slug = value
        .toLowerCase()
        .replaceAll(RegExp(r'[^a-z0-9]+'), '-')
        .replaceAll(RegExp(r'^-+|-+$'), '');
    return slug.isEmpty ? 'na' : slug;
  }

  static List<String> _parseStringList(dynamic raw) {
    if (raw == null) return [];
    return (raw as List<dynamic>).map((e) => e.toString()).toList();
  }
}
